name: Integration Tests - Features (AMD)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'torchtitan/experiments/**'

permissions:
  id-token: write
  contents: read

jobs:
  features:
    uses: ./.github/workflows/integration_test_features.yaml
    with:
      gpu-arch: rocm
    secrets: inherit
